### ISSUE TITLE
M117 (Set LCD Message) not handled correctly

### ISSUE THREAD

**Issue by Cerbrus** [ieatacid/OctoPrint-TerminalCommands#10]
The terminal commands aren't playing nicely with [`M117`](http://marlinfw.org/docs/gcode/M117.html).

When `M117` is the first command, like this:  
` M117 Reporting setting; M503`  
Then the commands after that aren't executed.

When `M117` appears at the end of a chain of commands:   
`M503; M117 Reporting setting`  
Then the string passed to `M117` is capitalized.

This means that command like these won't work:
`M117 Auto Homing; G28; M117 Auto Homing Done;`
`M117 Centering; G90; G0 Z5; G0 X117.5 Y117.5; G0 Z0; M117 Centered;`

**Comment by ieatacid** [comment]
I'll take a look when I get a chance. Probably Saturday at the earliest.

**Comment by Cerbrus** [comment]
Thanks for your quick response!

From what I can see, [these lines](https://github.com/ieatacid/OctoPrint-TerminalCommands/blob/master/octoprint_TerminalCommands/static/js/TerminalCommands.js#L48-L53) are probably responsible for capitalizing the string.

It looks like there's a blacklist this command may be missing from?

**Comment by ieatacid** [comment]
Weird. I copied that function right from OctoPrint, since it isn't public:

https://github.com/foosel/OctoPrint/blob/master/src/octoprint/static/js/app/viewmodels/terminal.js#L349

**Comment by Cerbrus** [comment]
Oh, that's interesting. I should have a look at what OctoPrint does when you directly submit the whole command in the terminal.

Maybe it's an OP bug.

**Comment by ieatacid** [comment]
Well, OctoPrint only expects one command at a time so multiple may throw an error or produce some weird output.

**Comment by ieatacid** [comment]
Try 0.1.6 (your code works for me now)

**Comment by Cerbrus** [comment]
I’ll have a look at it this evening 😃

**Comment by Cerbrus** [comment]
Sorry, I didn't get around to checking this, yet. Probably this evening.

**Comment by Cerbrus** [comment]
Yup! Works like a charm! Thanks for the quick fix!

Especially command like:

`M117 Moving to 0,0; G90; G0 Z5; G0 X0 Y0; G0 Z0; M117 Moved to 0,0`
Work nicely, as the last `M117` only gets logged after the move has finished.

For Auto home / ABL (G28 / G29), the last command executes before the system finished the operation, but I assume that's an OctoPrint limitation.
