### ISSUE TITLE
Ability to move to different tab

### ISSUE THREAD

**Issue by rameden** [ieatacid/OctoPrint-TerminalCommands#4]
This is a feature request. I was wondering if it would be possible to get the option to move to another tab. I would use this WAY more if it was in my control tab. 

Thanks for this great plugin

**Comment by ieatacid** [comment]
https://plugins.octoprint.org/plugins/customControl/

I made this plugin because I had some custom control commands that just triggered terminal output.

And the custom control plugin is way more customizable.

**Comment by rameden** [comment]
Didn't even know that was a thing. Thanks a ton!
