### ISSUE TITLE
Buttons enabled in read only mode.

### ISSUE THREAD

**Issue by tonejaco** [ieatacid/OctoPrint-TerminalCommands#7]
This is a very minor issue but when the user is not logged in the buttons are enabled and you can click on them but they don't perform any action as they shouldn't. But ideally the button would be disabled (greyed out) for the read-only user. Alternately they might display a message that the buttons only perform an action when logged in.

**Comment by ieatacid** [comment]
Ok, thanks for the report. I'll take care of it.
