### ISSUE TITLE
Allow mixing of Python and GCode in macros

### ISSUE THREAD

**Issue by jackbradach** [ieatacid/OctoPrint-TerminalCommands#8]
Terminal macros are awesome; I've made buttons for most of my jankity-ass printer's preflight steps making a reset much quicker.  I had a couple more areas I could automate with them, but I need variables to do so.  For example, I have a couple "Nudge Z" buttons that I use to fine tune the offset between my extruder and BLTouch.  I'd like to have a "Store Z Offset," but that'd require something like:

<code>$z_offset = M92; M851 Z $z_offset</code>

...which of course wouldn't work with pure GCode.  Have you considered adding the ability to call a Python function?  That'd also provide some interesting use cases, like reacting to feedback from the printer during a macro.

**Comment by ieatacid** [comment]
Have you looked at [Custom Control Editor](https://plugins.octoprint.org/plugins/customControl/)? It supports [Parameterized GCODE Script](http://docs.octoprint.org/en/master/features/custom_controls.html#id9).

**Comment by jackbradach** [comment]
I have not, but that looks pretty snazzy.  Thanks!
